---
title: "Chain Diagnostics"
author: "Detian Deng"
date: "September 3, 2015"
output: html_document
---

Acceptance Rate
```{r, echo=FALSE, fig.width=12, fig.height=12}
load("~/Documents/workspace/mu_0.12pi0_0.05pi_0.35.RData")
tmp = Posterior
apply(tmp$history.accept[2500:5000,],2,mean)

library(coda)
mc.chain = mcmc(tmp$posterior[2500:5000,],thin=1)
plot(mc.chain)

```

Compare the Truth, MLE, Posterior Estimates, and prior.
```{r, echo=FALSE}
est.compare
mc.est = c(round(summary(mc.chain)$statistics[,1],3), rep(0,2))
est.compare[,3] = mc.est
```

Using a different burnin period.
```{r, echo=FALSE}
est.compare
```

Chain Diagnosis
```{r, echo=FALSE}
chain1 =  mcmc(tmp$posterior[1:2000,1:4])
# chain2 =  mcmc(tmp$posterior[-(1:2000),1:4])
# combinedchains = mcmc.list(chain1, chain2) 
# #plot(combinedchains)
# gelman.diag(combinedchains)
# gelman.plot(combinedchains)
# 
# chain1 =  mcmc(tmp$posterior[1:2000,-(1:4)])
# chain2 =  mcmc(tmp$posterior[-(1:2000),-(1:4)])
# combinedchains = mcmc.list(chain1, chain2) 
# #plot(combinedchains)
# gelman.diag(combinedchains)
# #gelman.plot(combinedchains)
```








